// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAepOJa_AG2C5Hi9ChZ-W5OQFHdlg2rZYE',
    appId: '1:47281990167:ios:8957c18c82801531b80a52',
    messagingSenderId: '47281990167',
    projectId: 'gradienteauth',
    storageBucket: 'gradienteauth.firebasestorage.app',
    androidClientId: '47281990167-qn4adhl3h8qfkvn5h51q9uq6oq4cb7ih.apps.googleusercontent.com',
    iosClientId: '47281990167-3414hg7sbjfh546o12j9prf3oret7ht4.apps.googleusercontent.com',
    iosBundleId: 'com.example.gradiente',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBG3cA5b5vSwkSnsO75pqL272dEucmNOFQ',
    appId: '1:47281990167:web:00dc57873bd74c7bb80a52',
    messagingSenderId: '47281990167',
    projectId: 'gradienteauth',
    authDomain: 'gradienteauth.firebaseapp.com',
    storageBucket: 'gradienteauth.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBG3cA5b5vSwkSnsO75pqL272dEucmNOFQ',
    appId: '1:47281990167:web:076554653031c756b80a52',
    messagingSenderId: '47281990167',
    projectId: 'gradienteauth',
    authDomain: 'gradienteauth.firebaseapp.com',
    storageBucket: 'gradienteauth.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAepOJa_AG2C5Hi9ChZ-W5OQFHdlg2rZYE',
    appId: '1:47281990167:ios:00f685491d5c5b2cb80a52',
    messagingSenderId: '47281990167',
    projectId: 'gradienteauth',
    storageBucket: 'gradienteauth.firebasestorage.app',
    androidClientId: '47281990167-qn4adhl3h8qfkvn5h51q9uq6oq4cb7ih.apps.googleusercontent.com',
    iosClientId: '47281990167-3414hg7sbjfh546o12j9prf3oret7ht4.apps.googleusercontent.com',
    iosBundleId: 'com.example.gradiente',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2fXCbJOJ8LjowKPLaISjATe1QRADOmC8',
    appId: '1:47281990167:android:f7ac637bfc97d16fb80a52',
    messagingSenderId: '47281990167',
    projectId: 'gradienteauth',
    storageBucket: 'gradienteauth.firebasestorage.app',
  );

}